#!/usr/bin/env bash

FLAG_FZF_ACTIVE_SESSIONS=0
FLAG_FROM_CURRENT_DIR=0

while [[ "$#" -gt 0 ]]; do
  case $1 in
    -s) FLAG_FZF_ACTIVE_SESSIONS=1; shift ;;
    -c) FLAG_FROM_CURRENT_DIR=1; shift ;;
    *) break ;;
  esac
done

HOME=~/
PERSONAL=~/personal
CONFIG=~/.config

tmux-active() {
  [[ -n $TMUX || -n $(pgrep tmux) ]]
}

switch-session() {
  if [[ -z $TMUX ]]; then
    tmux attach-session -t $1
  else
    tmux switch-client -t $1
  fi
}

has-session() {
  tmux list-sessions | grep "^$1:"
}

find-session() {
  tmux list-sessions | awk -F: '{print $1}' | grep "$1"
}

create-windows() {
  tmux rename-window -t $1:1 'nvim'
  tmux send-keys -t $1:1 'vim .' C-m

  tmux new-window -t $1 -dn 'long-running' -c $2
  tmux new-window -t $1 -dn 'cmd' -c $2
  tmux new-window -t $1 -dn 'extra' -c $2
}

partial-match-search() {
  matches=$(find-session "$1")

  if [[ -z "$matches" ]]; then
    echo "$1"
    return
  fi

  selected=$(echo -e "$matches\nCreate new session: $1" | fzf)

  if [[ "$selected" == "Create new session: $1" ]]; then
    echo "$1"
  else
    echo "$selected"
  fi
}

if [[ $FLAG_FZF_ACTIVE_SESSIONS -eq 1 ]] && tmux-active; then
  switch-session $(tmux list-sessions | awk -F: '{print $1}' | fzf)
  exit 0
fi

if [[ $# -eq 1 ]]; then
  selected=$(partial-match-search "$1")
  session_dir=$(pwd)
else
  if [[ $FLAG_FROM_CURRENT_DIR -eq 1 ]]; then
    session_dir=$(find $(pwd) -mindepth 1 -maxdepth 1 -type d | fzf)
  else
    session_dir=$(find $HOME $PERSONAL $CONFIG -mindepth 1 -maxdepth 1 -type d | fzf)
  fi

  if [[ -z $session_dir ]]; then
    exit 0
  fi
  selected=$session_dir
fi

session_name=$(basename "$selected" | tr . _)

if ! tmux-active; then
  tmux new-session -ds $session_name -c $session_dir
  create-windows $session_name $session_dir
  tmux attach -t $session_name
  exit 0
fi

if ! has-session $session_name; then
  tmux new-session -ds $session_name -c $session_dir
  create-windows $session_name $session_dir
fi

switch-session $session_name
