#!/usr/bin/env bash

HOME=~/
PERSONAL=~/personal
CONFIG=~/.config

tmux-active() {
  tmux_running=$(pgrep tmux)
  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    false
  else
    true
  fi
}

switch-session() {
  if [[ -z $TMUX ]]; then
    tmux attach-session -t $1
  else
    tmux switch-client -t $1
  fi
}

has-session() {
  tmux list-sessions | awk -F: '{print $1}' | grep -m1 "$1" > /dev/null
}

# Populate tmux session with windows
# Window 1 -> nvim
# Window 2 -> long running processes
# Window 3 -> cmd eg. git
# Window 4 -> extras / spare
create-windows() {
  tmux rename-window -t $1:1 'nvim'
  tmux send-keys -t $1:1 'vim .' C-m

  tmux new-window -t $1 -dn 'long-running' -c $2
  tmux new-window -t $1 -dn 'cmd' -c $2
  tmux new-window -t $1 -dn 'extra' -c $2
}

if [[ $# -eq 1 ]]; then
  selected=$1
  _pwd=$(pwd)
  session_dir=$(basename "$_pwd" | tr . _)
else
  session_dir=$(find $HOME $PERSONAL $CONFIG -mindepth 1 -maxdepth 1 -type d | fzf)
  if [[ -z $session_dir ]]; then
    exit 0
  fi
  selected=$session_dir
fi

session_name=$(basename "$selected" | tr . _)

if ! tmux-active; then
  tmux new-session -ds $session_name -c $session_dir
  create-windows $session_name $session_dir
  tmux attach -t $session_name
  exit 0
fi

if ! has-session $session_name; then
  tmux new-session -ds $session_name -c $session_dir
  create-windows $session_name $session_dir
fi

switch-session $session_name
